export const RABBIT_GLOBA_INTERCEPTOR = Symbol("RABBIT_GLOBA_INTERCEPTOR");
export const RABBIT_INTERCEPTOR = Symbol("RABBIT_INTERCEPTOR");
export const RABBIT_AUTH_GUARD = Symbol("RABBIT_AUTH_GUARD");
export const RABBIT_DECORATOR_KIND = Symbol("RABBIT_DECORATOR_KIND");

export const AUTH_GAURD_HANDLER = Symbol("AUTH_GUARD_HANDLER");
export const INTERCEPTOR_HANDLER = Symbol("INTERCEPTOR_HANDLER");
export const POST_INTERCEPTOR_HANDLER = Symbol("POST_INTERCEPTOR_HANDLER");

export const GRAPHQL = Symbol("GRAPHQL");
export const ENUM = Symbol("ENUM");
